# Import library

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu121


# Scalar

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# convert value of tensor to python value(numberical value)
scalar.item()

7

- A vector is a single dimension tensor but can contain many numbers.

- As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

- The important trend here is that a vector is flexible in what it can represent (the same with tensors).

# Vector

In [5]:
# A vector is a single dimension tensor but can contain many numbers.
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

- Hmm, that's strange, vector contains two numbers but only has a single dimension.
=> You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

In [7]:
vector.shape

torch.Size([2])

# Matrix

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

# Random tensors

In [11]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.dtype

(tensor([[0.1056, 0.8324, 0.6321, 0.0480],
         [0.4088, 0.6466, 0.2917, 0.0800],
         [0.7195, 0.7179, 0.8235, 0.5962]]),
 torch.float32)

In [12]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [13]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [14]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# Creating a range and tensors like

In [15]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten_deprecated, zero_to_ten

<ipython-input-15-3fddf8a79710>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [16]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [17]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

- dtype=None: This is the data type of the tensor. When dtype is set to None, PyTorch defaults to using torch.float32 (or the default data type that has been previously set). In this case, the tensor will have a float32 data type.

- device=None: This specifies the device where the tensor is stored (CPU or GPU). When device is set to None, the tensor is stored on the default device (typically the CPU unless otherwise specified).

- requires_grad=False: This parameter determines whether the tensor needs to track gradients (used for computation in neural network training). When requires_grad=False, the tensor will not retain gradients during computation.

In [18]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

# Getting information from tensors

In [19]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5290, 0.0086, 0.1757, 0.7747],
        [0.0669, 0.0548, 0.2664, 0.5417],
        [0.1530, 0.6859, 0.9712, 0.7609]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors (tensor operations)

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

# Basic operations

In [20]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [21]:
tensor * 10

tensor([10, 20, 30])

In [22]:
tensor - 10

tensor([-9, -8, -7])

In [23]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [24]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [25]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [26]:
# [1*1 + 2*2 + 3*3] = [14]
torch.matmul(tensor, tensor)

tensor(14)

In [27]:
tensor @ tensor

tensor(14)

The in-built torch.matmul() method is faster.

In [28]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 458 µs, sys: 0 ns, total: 458 µs
Wall time: 2.06 ms


tensor(14)

In [29]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 73 µs, sys: 0 ns, total: 73 µs
Wall time: 76.8 µs


tensor(14)

In [30]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [31]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


You can also use torch.mm() which is a short for torch.matmul().

In [32]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

- Module torch.nn.Linear() trong PyTorch – còn được gọi là một feed-forward layer hoặc fully connected layer – thực hiện phép nhân ma trận giữa một đầu vào x và một ma trận trọng số A. Công thức toán học cho một lớp Linear cơ bản là:
$$
y = x*A^T + b
$$
- Giải thích các thành phần:

  - x: Đầu vào của lớp. Trong mạng nơ-ron, x thường là đầu ra của lớp trước hoặc chính là dữ liệu đầu vào (hình ảnh, văn bản, v.v.).

  - A: Ma trận trọng số được tạo bởi lớp Linear. A bắt đầu với các giá trị ngẫu nhiên và được điều chỉnh qua quá trình huấn luyện để tối ưu hóa việc biểu diễn các mẫu trong dữ liệu. Ký hiệu A^T cho thấy ma trận này sẽ được chuyển vị trước khi thực hiện phép nhân với x.

  * Lưu ý: Ký hiệu cho ma trận trọng số có thể thay đổi tùy từng trường hợp, thường dùng W hoặc một ký hiệu khác, chẳng hạn như X trong một số tài liệu.

  - b: Hệ số bias giúp điều chỉnh một chút cho các trọng số và đầu vào, thường là một vector có số phần tử bằng số out_features của lớp Linear.

  - y: Đầu ra của lớp Linear, là một phiên bản đã được biến đổi của x, với hy vọng sẽ giúp phát hiện các mẫu trong dữ liệu qua mỗi lần tính toán.
- Công thức này tương tự như hàm tuyến tính y = mx + b bạn có thể đã thấy trong toán học, dùng để biểu diễn một đường thẳng.
________________________________________________________________________________
- Thử nghiệm với các tham số in_features và out_features
Trong PyTorch, bạn có thể thay đổi giá trị của in_features và out_features khi khởi tạo lớp torch.nn.Linear(), điều này sẽ thay đổi kích thước của ma trận trọng số A:
  - in_features xác định số lượng đầu vào, tương ứng với số cột của A.
  - out_features xác định số lượng đầu ra, tương ứng với số hàng của A.
- Khi bạn thay đổi các giá trị này, PyTorch sẽ tạo ra các ma trận trọng số A và hệ số bias b có kích thước tương ứng.

In [33]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [34]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


1. torch.manual_seed(42): Đặt hạt giống ngẫu nhiên là 42 để đảm bảo tính tái lặp cho các phép toán ngẫu nhiên, như khởi tạo trọng số trong lớp Linear. Nhờ đó, nếu bạn chạy lại mã, bạn sẽ nhận được cùng một kết quả ngẫu nhiên.
2. linear = torch.nn.Linear(in_features=2, out_features=6): Tạo một lớp Linear (lớp kết nối tuyến tính) với 2 đầu vào (in_features=2) và 6 đầu ra (out_features=6). Lớp Linear này thực hiện phép biến đổi tuyến tính cho đầu vào
𝑥 theo công thức:
$$
𝑦=𝑥*𝑊^𝑇+𝑏
$$
- Trong đó:
  - 𝑥 là đầu vào.
  - 𝑊 là ma trận trọng số có kích thước out_features * in_features (6 x 2),
  - 𝑏 là vector bias có kích thước out_features (6).
- Khi lớp Linear được tạo, các trọng số và bias sẽ được khởi tạo ngẫu nhiên.
3. x = tensor_A: Gán biến x là một tensor đầu vào có tên tensor_A. Kích thước của x phải phù hợp với số lượng đầu vào (in_features=2) mà lớp Linear yêu cầu.
4. output = linear(x): Tính đầu ra bằng cách đưa x qua lớp Linear. Đầu ra sẽ có kích thước [batch_size, out_features], trong đó batch_size là số lượng mẫu trong x (nếu x là một batch các mẫu).
5. In kết quả: Cuối cùng, đoạn mã in ra kích thước của đầu vào và đầu ra của phép biến đổi, giúp bạn xác định kích thước dữ liệu sau khi qua lớp Linear.
6. Ví dụ về output
  1. Input shape: [batch_size, 2]: Đầu vào có kích thước [batch_size, 2], với 2 là số lượng đầu vào cho lớp Linear.
  2. Output shape: [batch_size, 6]: Đầu ra có kích thước [batch_size, 6], với 6 là số lượng đầu ra của lớp Linear.

# Finding the min, max, mean, sum, etc (aggregation)

In [35]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [37]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

# Positional min/max

In [38]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


# Change tensor datatype

In [39]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [40]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [41]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

# Reshaping, stacking, squeezing and unsqueezing

In [42]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [43]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [44]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [45]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [46]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [47]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [48]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

In [49]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [51]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [52]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [53]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [54]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

# PyTorch tensors & NumPy

- Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.
- The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
  - torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
  - torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [55]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [56]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [57]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [58]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

In [59]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [60]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running tensors on GPUs (and making faster computations)


1. Getting a GPU

In [61]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [62]:
import tensorflow as tf
import timeit

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print(
      '\n\nThis error most likely means that this notebook is not '
      'configured to use a GPU.  Change this in Notebook Settings via the '
      'command palette (cmd/ctrl-shift-P) or the Edit menu.\n\n')
  raise SystemError('GPU device not found')

def cpu():
  with tf.device('/cpu:0'):
    random_image_cpu = tf.random.normal((100, 100, 100, 3))
    net_cpu = tf.keras.layers.Conv2D(32, 7)(random_image_cpu)
    return tf.math.reduce_sum(net_cpu)

def gpu():
  with tf.device('/device:GPU:0'):
    random_image_gpu = tf.random.normal((100, 100, 100, 3))
    net_gpu = tf.keras.layers.Conv2D(32, 7)(random_image_gpu)
    return tf.math.reduce_sum(net_gpu)

# We run each op once to warm up; see: https://stackoverflow.com/a/45067900
cpu()
gpu()

# Run the op several times.
print('Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images '
      '(batch x height x width x channel). Sum of ten runs.')
print('CPU (s):')
cpu_time = timeit.timeit('cpu()', number=10, setup="from __main__ import cpu")
print(cpu_time)
print('GPU (s):')
gpu_time = timeit.timeit('gpu()', number=10, setup="from __main__ import gpu")
print(gpu_time)
print('GPU speedup over CPU: {}x'.format(int(cpu_time/gpu_time)))

Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images (batch x height x width x channel). Sum of ten runs.
CPU (s):
16.598810345999993
GPU (s):
0.31959677200001124
GPU speedup over CPU: 51x


2. Getting PyTorch to run on the GPU

In [63]:
import torch
torch.cuda.is_available()

True

In [64]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device_name

'/device:GPU:0'

In [65]:
# Count number of devices
torch.cuda.device_count()

1

3. Putting tensors (and models) on the GPU

In [66]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
# tensor_on_gpu.numpy()

- Lỗi xảy ra vì PyTorch không cho phép chuyển trực tiếp một tensor nằm trên GPU thành một mảng NumPy. Tensor cần được chuyển về CPU trước khi thực hiện thao tác này, vì NumPy chỉ hoạt động với dữ liệu nằm trên CPU.

In [68]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [69]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')